### ISSUE TITLE
Service Page - Issue while create due date

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1453]
**Describe the bug**
- when adding more characters in due date type field it show database error
https://www.berrycast.com/conversations/680175ac-c1ff-54b5-839b-b91c5ac8bd91

**Comment by mitulpanch** [comment]
This is probably solved by now, but not sure, so forwarding this in verification

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/dff9d9e1-f642-5c9d-a14c-00c2fa8fc8f9
issue still exist

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/36d61b84-f093-573d-82ff-a48e0657fea4
